first_number = int(input('Enter your first number: '))
second_number = int(input('Enter your second number: '))

print('{} + {} = '.format(first_number, second_number))
print(first_number + second_number)
print('{} - {} = '.format(first_number, second_number))
print(first_number - second_number)
print('{} * {} = '.format(first_number, second_number))
print(first_number * second_number)
print('{} / {} = '.format(first_number, second_number))
print(first_number / second_number)